Introduced flag for keeping VMs alive
AlmaLinux/alts pull request #110
Opened 2024-12-12 00:36 UTC by Kwaizer

Resolves: https://cloudlinux.atlassian.net/browse/AL-5654
Fronend and backend: https://gerrit.cloudlinux.com/c/build-system/+/181258

2024-12-13 13:41 UTC, javihernandez approved these changes

2024-12-17 17:50 UTC, Kwaizer commented on alts/worker/tasks.py
> +    vm_alive = task_params.get('vm_alive')
I made adjustment but as I understand we need also to pass this flag to DockerRunner in order to avoid an exception during initialization.

2024-12-24 08:46 UTC, anfimovdm requested changes

2024-12-24 08:46 UTC, anfimovdm commented on alts/worker/runners/opennebula.py
> +            vm_alive= vm_alive,
please remove whitespace before `vm_alive`

2025-01-09 12:48 UTC, anfimovdm approved these changes

2025-01-20 11:26 UTC, merged